/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz4a;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {


    //ตัวอย่าง 1 ให้สร้าง Employee Employee(1, "John Doe", 50000) และตรวจสอบว่าเงินเดือน เป็น 50000

    /**
     * 
     */
    @Test void createEmployee() {
        public Employee(int employeeId, String name, double salary) {
            this.employeeId = employeeId;
            this.name = name;
            this.salary = (salary > 0) ? salary : 0;
        
    }
    public double calculateSalary() {
        return salary;
    }

    
    public int getEmployeeId() {
        return employeeId;
    }

   
    public String getName() {
        return name;
    }
}

    //ข้อ 2 ตรวจสอบว่า Salary ตั้งให้ติดลบไม่ได้
    @Test void SalaryCannotBeNegative() {
 
    }

    //ข้อ 3 ตรวจสอบว่า Bonus เป็น 20% ของ เงินเดือน(Salary)
    //ต้องมีการแก้ไข code ใน Manager.java ให้ถูกต้อง
    /**
     * 
     */
    @Test void Bonus20() {
        /**
         * @param employeeId
         * @param name
         * @param salary
         * @param department
         * @param bonus
         */
        public void Manager(int employeeId, String name, double salary, String department, double bonus) {
    }
    super(employeeId, name, salary);
    this.department = department;
    this.bonus = bonus;
}

// 2.3
public void displayDetails(String bonus) {
    String department = null;
       
         final String[] details = {
         "Employee ID: " + getEmployeeId(),
         "Name: " + getName(),
         "Salary: " + calculateSalary(),
         "Department: " + department,
         "Bonus: " + bonus
 };
        for (String detail : details) {
            System.out.println(detail)
        }
     }
                                        
                                        private String getName() {
                    // TODO Auto-generated method stub
                    throw new UnsupportedOperationException("Unimplemented method 'getName'");
                }
                
                                        private String calculateSalary() {
                    // TODO Auto-generated method stub
                    throw new UnsupportedOperationException("Unimplemented method 'calculateSalary'");
                }
                
                        private String getEmployeeId() {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'getEmployeeId'");
        }
}